name=zahosts-health
service=whostmgr
url=/cgi/zahosts_health/index.php
user=root
acls=all
displayname=Zahosts Health
entryurl=zahosts_health/index.php
target=_self
searchtext=health mail queue dnsbl backup autossl wordpress security deliverability zahosts
